### ISSUE TITLE
Excel data file is corrupt

### ISSUE THREAD

**Issue by atsats** [TrainingByPackt/Data-Science-Projects-with-Python#4]
The Excel data file 'default_of_credit_card_clients__courseware_version_1_21_19.xls' appears to be corrupt. It produces a warning in Excel and does not open in read_excel():
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'\n\n\n\n\n<!D'

**Comment by klostest** [comment]
@atsats I am able to open the file in Excel and in Pandas. Perhaps trying cloning the repo again, or downloading the file individually, as you may have had an issue with your download becoming corrupted. If you're still having issues, could you indicate your Pandas version and other details of your system?

**Comment by Tomyzon1728** [comment]
Can I add a loan prediction project based on Matplotlib, numpy and pandas .

**Comment by klostest** [comment]
Hi @Tomyzon1728, this sounds like a separate issue. If you are suggesting adding a new project to this repo, that would not be appropriate since the repo consists only of the code demonstrated in the accompanying book. However if you have questions or comments related to the book, please use the form on my website: https://www.steveklosterman.com/book/. Thanks!

@atsats I'm assuming your issue has been resolved by now. If not please feel free to reopen this issue. Thank you.
